
## defaults for _all_ profiles
[default]
port = 8000
# limits = { form = "64 kB", json = "1 MiB" }
#qx_data_dir = "~/.qx/data"
database_url = "sqlite://db/qxdb.sqlite"

[default.oauth.google]
provider = "Google"
client_id = "<client-id>"
client_secret = "<client-secret>"
redirect_uri = "http://localhost:8000/auth/google"

[tls]
certs = "private/rsa_sha256_cert.pem"
key = "private/rsa_sha256_key.pem"

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
## only the `json` key from `default` will be overridden; `form` will remain
# limits = { json = "10MiB" }
#qx_oc_test_data_dir = "tests/oc/data"

#[default.databases.qxdb]
#url = "sqlite:///tmp/qxdb.sqlite"

[demo]
qx_create_demo_event = true

## set only when compiled in release mode, i.e, `cargo build --release`
[release]
address = "0.0.0.0"
# port = 9999
ip_header = false
secret_key = "hPrYyЭRiMyµ5sBB1π+CMæ1køFsåqKvBiQJxBVHQk="
