openapi: 3.0.3
info:
  title: QuickEvent exchange httpd - OpenAPI 3.0
  description: |-
    This is QuickEvent exchange server based on the OpenAPI 3.0 specification.

    Some useful links:
    - [The Quick Event repository](https://github.com/Quick-Event/quickbox)
  version: 0.0.1
paths:
  /event:
    get:
      tags:
        - qxhttpd
      summary: Get event list html page
      operationId: eventList
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Invalid event key
  /event/{eventKey}:
    get:
      tags:
        - qxhttpd
      summary: Get event info html page
      operationId: eventInfo
      parameters:
      - name: eventKey
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventKey'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Invalid event key
  /api/event:
    post:
      tags:
        - qxhttpd
      summary: Register event
      # description: Add a new pet to the store
      operationId: registerEvent
      requestBody:
        # description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventDefinition'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /api/event/{eventKey}/ochecklist:
    post:
      tags:
        - O-CheckList
      summary: Add new O-Checklist change set
      # description: Add a new pet to the store
      operationId: addOChecklistChangeSet
      parameters:
      - name: eventKey
        in: path
        description: Event key generated by Quick Event
        required: true
        schema:
          $ref: '#/components/schemas/EventKey'
      requestBody:
        # description: Create a new pet in the store
        content:
          application/yaml:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OChecklistRunner'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OChecklistRunner'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid input
        '422':
          description: Validation exception
    get:
      tags:
        - O-CheckList
      summary: Read change set list
      # description: Add a new pet to the store
      operationId: listOChecklistChangeSets
      parameters:
      - name: eventKey
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventKey'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChangeSetId'
        '404':
          description: Invalid event key
  /api/event/{eventKey}/qe/chng/in/{changeSetId}:
    get:
      tags:
        - QuickEvent
      summary: Read change set
      operationId: getQEChangeSet
      parameters:
      - name: eventKey
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventKey'
      - name: changeSetId
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ChangeSetId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QERunChangeSet'
        '404':
          description: Invalid event key
  /api/event/{eventKey}/qe/startListIOF30Xml:
    get:
      tags:
        - QuickEvent
      summary: Read actual start list
      # description: Add a new pet to the store
      operationId: startListIOF30Xml
      parameters:
      - name: eventKey
        in: path
        description: Event key generated by Quick Event
        required: true
        schema:
          $ref: '#/components/schemas/EventKey'
      responses:
        '200':
          description: Successful operation
          content:
            application/xml:
              schema:
                type: string
        '404':
          description: Invalid event key
components:
  schemas:
    EventDefinition:
      properties:
        eventKey:
          $ref: '#/components/schemas/EventKey'
        name:
          type: string
        date:
          type: string
        place:
          type: string
      required:
      - eventKey
    EventKey:
      type: string
      description: Event key generated by Quick Event
    OChecklistRunner:
      properties:
        Id:
          type: string
          format: int64
          example: 1234
        StartStatus:
          type: string
          enum:
          - Started OK
          - Did not start (DNS)
          - Late start
        Card:
          type: integer
          format: int64
          example: 123456
        ClassName:
          type: string
          # format: int64
          example: H21
        Name:
          type: string
          # format: int64
          example: John Doe
        StartTime:
          type: string
          pattern: "^[0-2][0-9]:[0-5][0-9]:[0-5][0-9]$"
          example: 17:18:59
        Comment:
          type: string
    ChangeSetId:
      type: string
      pattern: "^[0-9]{6}$"
      example: "2024-02-13T15-08-59-789"
    Time:
      type: string
      pattern: "^[0-2][0-9]:[0-5][0-9]:[0-5][0-9](.[0-9]+)?$"
      example: 17:18:59.123
    DateTime:
      type: string
      pattern: "^20[0-9]{2}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9](.[0-9]+)?$"
      example: 17:18:59.123
    QERecord:
      properties:
        table:
          type: string
          enum:
          - runs
          - radio

        # common fields
        siId:
          type: integer
          format: int64
          example: 123456

        # table runs
        id:
          type: integer
          format: int64
          example: 1234
        checkTime:
          $ref: '#/components/schemas/EventKey'
        comment:
          type: string

        # table radio
        punchTime:
          $ref: '#/components/schemas/EventKey'
